
require:
 - rubocop-rails

Rails:
  Enabled: true

AllCops:
 TargetRubyVersion: 3.0
 NewCops: disable

Layout/LineLength:
 Max: 120

Style/FrozenStringLiteralComment:
 Enabled: false

Style/Documentation:
 Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: true